baseurl: /test
url: https://aalister.github.io
theme: null
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  math_engine: katex
include:
 - _layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "assets"
    values:
      layout: null
