# Site settings
baseurl: /test
url: https://aalister.github.io
theme: null
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "assets/"
    values:
      test: rabbit
