baseurl: /test
url: https://aalister.github.io
theme: null
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
include:
 - _layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: _default
  -
    scope:
      path: "assets"
    values:
      layout: null
